---
- hosts: app-server
  become: yes
  tasks:
      - name: Copy docker compose to target vm 
        copy:
          src: ../../docker-compose.yml
          dest: "{{ env.spring_app_dest }}"

      - name: Run docker compose up again
        community.docker.docker_compose_v2:
          project_src: "{{ env.spring_app_dest }}"
        register: output
