---
- hosts: app-server
  become: yes
  tasks:
      - name: Install Java
        apt:
          name: openjdk-21-jdk
          state: present
          update_cache: yes
      - name: Get Project From Github
        git:
          repo: "{{ env.spring_app_repo }}"
          dest: "{{ env.spring_app_dest }}"
          version: "{{ env.spring_app_version }}"
          force: yes
      
      - name: Run Application with Docker Compose
        become: yes
        shell:
          "cd {{ env.spring_app_dest }} && docker compose up --build"